import Head from "next/head";
import Toolbar from "../components/Toolbar";
import ImageUrlBuilder from "@sanity/image-url";
import BlockContent from "@sanity/block-content-to-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
export default function Home({ posts }) {
  const router = useRouter();
  const [mappedPosts, setMappedPosts] = useState([]);
  console.log(mappedPosts);
  useEffect(() => {
    if (posts.length) {
      const imgBuilder = ImageUrlBuilder({
        projectId: "qc7kts2y",
        dataset: "production",
      });

      setMappedPosts(
        posts.map((post) => {
          return {
            ...post,
            mainImage: imgBuilder.image(post.mainImage),
          };
        })
      );
    } else {
      setMappedPosts([]);
    }
  }, [posts]);
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <div className="m-10 sm:m-auto sm:w-[500px] md:w-[700px] pt-10">
        {mappedPosts.reverse().length ? (
          mappedPosts.map((post, index) => (
            <div
              className="cursor-pointer group my-10 border p-10 border-gray-50 shadow-lg hover:bg-gray-100"
              onClick={() => router.push(`/posts/${post.slug.current}`)}
              key={index}
            >
              <div className="relatvie flex justify-between group-hover:text-blue-400">
                <h1 className="font-semibold text-[38px] tracking-widest line-clamp-1">
                  {post.title}
                </h1>
                <p className="relative top-6">{post._createdAt}</p>
              </div>
              <img className="w-full" src={post.mainImage} alt="imageURL" />
              <div className="group-hover:text-blue-400 line-clamp-5 mt-6">
                <BlockContent blocks={post.body} />
              </div>
            </div>
          ))
        ) : (
          <>No posts yet</>
        )}
      </div>
    </div>
  );
}

export async function getServerSideProps(Context) {
  const query = encodeURIComponent(`*[ _type == "post" ]`);

  const url = `https://qc7kts2y.api.sanity.io/v1/data/query/production?query=${query}`;

  const result = await fetch(url).then((res) => res.json());
  if (!result.result || !result.result.length) {
    return {
      props: {
        posts: [],
      },
    };
  } else {
    return {
      props: {
        posts: result.result,
      },
    };
  }
}
